### ISSUE TITLE
Still need password to run as root (Mint Cinnamon 19.1)

### ISSUE THREAD

**Issue by Cryptobob24** [collinss/Cinnamon-Command-Launcher#1]
@collinss  I'm not sure if this is an error or if this is how it is meant to function, but even with 'run as root' option checked; I'm still asked to input my password each time before it runs the command. Is there anyway that I could include my password in the command or something so it will just run with root privileges when using hot keys or single button click? I'd greatly appreciate the help. I'm running Linux Mint Cinnamon 19.1, thanks!

**Comment by collinss** [comment]
> Is there anyway that I could include my password in the command or something so it will just run with root privileges when using hot keys or single button click?

Not that I know of, but there may be. The idea here was to allow the user to still be able to run commands that require root privileges and pop up a dialog that prompts for a password. Unfortunately, this is messy stuff, and I don't think I ever got this working as well as I wanted to.

If you do figure out a way to make it work better, you are always welcome to submit a pull request for it to https://github.com/linuxmint/cinnamon-spices-applets, but otherwise I don't plan to do much with this, as I spend most of my coding time on Mint itself now.
